"""
Django settings for YamagotiProjects project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3(&zari4^u-6iv$+z_2r2(oviwyj5g#cy*3c$t#x_=-w7cijv1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".ngrok-free.app",
    ".ngrok-free.dev",
    "verbless-sadistically-jayceon.ngrok-free.dev",
]

# Application definition

INSTALLED_APPS = [
    "channels",
    'simplepro',
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'AppleStockChecker.apps.ApplestockcheckerConfig',
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    # 'easyaudit',
    "django_celery_beat",  # 定时任务(可在Admin里改间隔/暂停)
    "django_celery_results",  # 可选：任务结果持久化到DB
    "django_filters",
    "buyrisk",  # 买方库存风控决策

]

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',  # 可选
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # "YamagotiProjects.middleware.login_required.LoginRequiredMiddleware",
    'django.middleware.common.CommonMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'easyaudit.middleware.easyaudit.EasyAuditMiddleware',
    'simplepro.middlewares.SimpleMiddleware'
]

ROOT_URLCONF = 'YamagotiProjects.urls'

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
}

try:
    if DEBUG:  # noqa: F821
        REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append(
            "rest_framework.renderers.BrowsableAPIRenderer"
        )
except NameError:
    pass

# ---- SimpleJWT ----
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # 如需与环境变量 SECRET_KEY 分离，可自定义 SIGNING_KEY
    # "SIGNING_KEY": os.getenv("JWT_SECRET", SECRET_KEY),
}

# ---- OpenAPI 文档 ----
SPECTACULAR_SETTINGS = {
    "TITLE": "Project API",
    "DESCRIPTION": "Django REST Framework + JWT",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [{"BearerAuth": []}],  # 文档右上角 Authorize 会显示 BearerAuth
    "COMPONENT_SPLIT_REQUEST": True,
}

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://127.0.0.1:8000",
    "https://verbless-sadistically-jayceon.ngrok-free.dev"

]
# 若你在本地调试 CSRF：
CSRF_TRUSTED_ORIGINS = ["http://localhost:3000",
                        "http://127.0.0.1:3000",
                        "http://127.0.0.1:8000",
                        "https://verbless-sadistically-jayceon.ngrok-free.dev"
                        ]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                "django.template.context_processors.debug",
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WHITENOISE_MAX_AGE = 60 * 60 * 24 * 7
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

WSGI_APPLICATION = 'YamagotiProjects.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 数据库配置：支持环境变量和 PgBouncer
USE_PGBOUNCER = os.getenv("USE_PGBOUNCER", "false").lower() == "true"

if USE_PGBOUNCER:
    # 通过 PgBouncer 连接（生产环境推荐）
    # PgBouncer 使用事务池模式，连接配置需要特殊处理
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("PGBOUNCER_DATABASE", "applestockchecker_dev"),
            "USER": os.getenv("PGBOUNCER_USER", "samuelzhu"),
            "PASSWORD": os.getenv("PGBOUNCER_PASSWORD", "Xdb73008762"),
            "HOST": os.getenv("PGBOUNCER_HOST", "127.0.0.1"),
            "PORT": os.getenv("PGBOUNCER_PORT", "6432"),
            # PgBouncer 事务池模式下，CONN_MAX_AGE 必须为 0
            # 因为 PgBouncer 会在每个事务结束后回收连接
            "CONN_MAX_AGE": 0,
            "CONN_HEALTH_CHECKS": True,  # Django 4.1+ 健康检查
            "OPTIONS": {
                # 禁用服务器端游标，PgBouncer 事务池模式不支持
                "options": "-c statement_timeout=60000",
            },
            "DISABLE_SERVER_SIDE_CURSORS": True,  # 关键：PgBouncer 必须禁用
        }
    }
else:
    # 直接连接 PostgreSQL（开发环境）
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DATABASE", "applestockchecker_dev"),
            "USER": os.getenv("POSTGRES_USER", "samuelzhu"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD", "Xdb73008762"),
            "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
            "PORT": os.getenv("POSTGRES_PORT", "5433"),
            "CONN_MAX_AGE": 60,  # 连接复用
            "CONN_HEALTH_CHECKS": True,
            "OPTIONS": {
                "options": "-c statement_timeout=60000",
            },
        }
    }
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja-jp'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"  # collectstatic 产物目录（生产/统一对外）
STATICFILES_DIRS = [
    BASE_DIR / "static",  # 你自己的前端静态目录（可选）
]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",  # 从各 app 的 /static/ 里找（第三方主题用这个）
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EXTERNAL_TRADEIN_SOURCES = [
    # {"name": "shop10", "url": "https://api.webscraper.io/api/v1/scraping-job/34172531/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    {"name": "shop9",
     "url": "https://api.webscraper.io/api/v1/scraping-job/34172581/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop8", "url": "https://api.webscraper.io/api/v1/scraping-job/34171950/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop7", "url": "https://api.webscraper.io/api/v1/scraping-job/34172579/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop6-1", "url": "https://api.webscraper.io/api/v1/scraping-job/34172574/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop6-2", "url": "https://api.webscraper.io/api/v1/scraping-job/34172575/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop6-3", "url": "https://api.webscraper.io/api/v1/scraping-job/34172576/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop6-4", "url": "https://api.webscraper.io/api/v1/scraping-job/34172578/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop5-1",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172561/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop5-2",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172563/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop5-3",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172572/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop5-4",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172573/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop4",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/	34172559/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    {"name": "shop3",
     "url": "https://api.webscraper.io/api/v1/scraping-job/34172550/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    {"name": "shop2",
     "url": "https://api.webscraper.io/api/v1/scraping-job/34478442/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},

    # # 样例：B 平台
    # {"name": "shop10", "url": "https://api.webscraper.io/api/v1/scraping-job/34172531/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
]

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# 优先级：settings > 环境变量 > 项目内默认文件
EXTERNAL_IPHONE17_INFO_PATH = BASE_DIR / "AppleStockChecker" / "data" / "iphone17_info.csv"

# WebScraper Cloud API 访问令牌（在 Web Scraper Cloud 的 API 页面可见）
WEB_SCRAPER_API_TOKEN = "vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"

# 导出地址模板（如官方变更，可在这里改）
# WEB_SCRAPER_EXPORT_URL_TEMPLATE = "https://api.webscraper.io/api/v1/scraping-job/{job_id}/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"
WEB_SCRAPER_EXPORT_URL_TEMPLATE = "https://api.webscraper.io/api/v1/scraping-job/{job_id}/csv"

# Webhook 共享密钥：在 WebScraper Cloud 的 webhook URL 上带 ?token=XXXX，或在 Header 里带 X-Webhook-Token
WEB_SCRAPER_WEBHOOK_TOKEN = "0BkhVQJQPDe4IPfxfnw9bX8hYzxY29D48uGi8zq8TcjbsMIvXShEzaEJFFAj"

# 可选：把 WebScraper 的 sitemap 名 或 job 上的 custom_id 映射为清洗器名（shop3/shop4…）
WEB_SCRAPER_SOURCE_MAP = {
    "shop1": "shop1",
    "shop2": "shop2",
    "shop3": "shop3",
    "shop4": "shop4",
    "shop5-1": "shop5-1",
    "shop5-2": "shop5-2",
    "shop5-3": "shop5-3",
    "shop5-4": "shop5-4",
    "shop6-1": "shop6-1",
    "shop6-2": "shop6-2",
    "shop6-3": "shop6-3",
    "shop6-4": "shop6-4",
    "shop7": "shop7",
    "shop8": "shop8",
    "shop9": "shop9",
    "shop10": "shop10",
    "shop11": "shop11",
    "shop12": "shop12",
    "shop13": "shop13",
    "shop14": "shop14",
    "shop15": "shop15",
    "shop16": "shop16",
    "shop17": "shop17",
    "shop18": "shop18",
    "shop19": "shop19",
    "shop20": "shop20",
}

# 部属用
# WEB_SCRAPER_WEBHOOK_TOKEN = os.getenv("WEB_SCRAPER_WEBHOOK_TOKEN", "")

# 开发用
WEB_SCRAPER_WEBHOOK_TOKEN = "XNgCZCQN7dvkSP7K17xmK8aq-6_bjvI_"

# Celery/Redis
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TASK_TIME_LIMIT = 600
CELERY_TASK_SOFT_TIME_LIMIT = 540
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Tokyo"
CELERY_ENABLE_UTC = False
CELERY_TASK_ACKS_LATE = True  # 任务跑完才确认，异常能重派
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # WorkerLost 也回到队列
CELERY_TASK_TRACK_STARTED = True

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
                    'code', 'subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable', ],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side', '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells',
                               'tableProperties', 'tableCellProperties'],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h3', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h5', 'title': 'Heading 3', 'class': 'ck-heading_heading3'},

            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}
SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_ACTION = True
SIMPLEUI_ANALYSIS = False

SIMPLEPRO_SECRET_KEY = '2c4411a795534e0fbc28720051161434'
SIMPLEPRO_MONIT_DISPLAY = True
SIMPLEPRO_INFO = True
SIMPLEPRO_FK_ASYNC_DATA = True

# SIMPLEUI_HOME_PAGE = "/admin-home"
SIMPLEUI_HOME_ICON = 'fa fa-user'

SIMPLEUI_CONFIG = {
    'system_keep': True,
    'dynamic': False,
    'menu_display': ['iPhone関連データ', ],
    'menus':
        [
            {
                'name': 'iPhone関連データ',
                'icon': 'fa-solid fa-mobile-screen-button',
                'models': [{'name': '中古店価格推移(',
                            'icon': 'fa-solid fa-chart-line',
                            'url': '/AppleStockChecker/analysis-dashboard/',
                            },
                           {'name': '实时图表',
                            'icon': 'fa-solid fa-store',
                            'url': '/AppleStockChecker/statistical-data-summary/',
                            },
                           {'name': '中古店価格ボード',
                            'icon': 'fa-solid fa-table-columns',
                            'url': '/AppleStockChecker/price-matrix/',
                            },
                           {'name': 'iPhone公式在庫表',
                            'icon': 'fa-solid fa-warehouse',
                            'url': '/AppleStockChecker/price-matrix/',
                            },

                           {'name': '中古店価格メタデータ',
                            'icon': 'fa-solid fa-database',
                            'models': [{'name': 'iPhoneモデル',
                                        'icon': 'fa-solid fa-mobile-button',
                                        'url': '/admin/AppleStockChecker/iphone/',
                                        },
                                       {'name': '中古店',
                                        'icon': 'fa-solid fa-shop',
                                        'url': '/admin/AppleStockChecker/secondhandshop/'
                                        },
                                       {'name': '中古店価格記録',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/purchasingshoppricerecord/'
                                        },
                                       {'name': '价格整形记录',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/purchasingshoptimeanalysis/'
                                        },

                                       {'name': '基础统计featuresnapshot-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/featuresnapshot/'
                                        },
                                       {'name': '参数空间featurespec-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/featurespec/'
                                        },

                                       {'name': '统计模型modelartifact-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/modelartifact/'
                                        },
                                       {'name': '预测模型forecastsnapshot-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/forecastsnapshot/'
                                        },
                                       {'name': 'cohortbar-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/cohortbar/'
                                        },

                                       {'name': 'cohortmember-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/cohortmember/'
                                        },
                                       {'name': 'cohort-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/cohort/'
                                        },
                                       {'name': 'overallbar-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/overallbar/'
                                        },
                                       {'name': 'shopweightitem-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/shopweightitem/'
                                        },
                                       {'name': 'shopweightprofile-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/shopweightprofile/'
                                        },


                                       ]
                            },
                           {'name': 'iPhone公式在庫メタデータ',
                            'icon': 'fa-solid fa-file-contract',
                            'models': [{'name': 'Apple公式ストア',
                                        'icon': 'fa-solid fa-store',
                                        'url': '/admin/AppleStockChecker/officialstore/',
                                        },
                                       {'name': 'iphone官方在库記録',
                                        'icon': 'fa-solid fa-truck-ramp-box',
                                        'url': '/admin/AppleStockChecker/inventoryrecord/'
                                        },
                                       ]
                            },
                           {'name': '临时页面',
                            'icon': 'fa-solid fa-file-contract',
                            'models': [
                                {'name': '価格推移(Model別)',
                                 'icon': 'fa-solid fa-chart-line',
                                 'url': '/AppleStockChecker/resale-trend-colors-merged/',
                                 },
                                {'name': '间隔',
                                 'icon': 'fa-solid fa-chart-line',
                                 'url': '/admin/django_celery_beat/intervalschedule/',
                                 },
                                {'name': '计划任务',
                                 'icon': 'fa-solid fa-chart-line',
                                 'url': '/admin/django_celery_beat/crontabschedule/',
                                 },
                                {'name': '日程时间',
                                 'icon': 'fa-solid fa-chart-line',
                                 'url': '/admin/django_celery_beat/solarschedule/',
                                 },
                                {'name': '定时',
                                 'icon': 'fa-solid fa-chart-line',
                                 'url': '/admin/django_celery_beat/clockedschedule/',
                                 },

                                {'name': '周期性任务',
                                 'icon': 'fa-solid fa-chart-line',
                                 'url': '/admin/django_celery_beat/periodictask/',
                                 },
                                {'name': '用户',
                                 'icon': 'fa-solid fa-chart-line',
                                 'url': '/admin/auth/user/',
                                 },
                                {'name': '组',
                                 'icon': 'fa-solid fa-chart-line',
                                 'url': '/admin/auth/group/',
                                 },

                            ]
                            },
                           ]
            },

        ]}

# --- 本地开发：允许 Session 认证 + JWT；生产保持只有 JWT ---
if os.getenv("DJANGO_ENV", "dev") == "dev":
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework.authentication.SessionAuthentication",  # 浏览器登录态
            "rest_framework_simplejwt.authentication.JWTAuthentication",  # 保留 JWT
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticated",
        ],
    }
else:
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework_simplejwt.authentication.JWTAuthentication",
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticated",
        ],
    }


DJANGO_EASY_AUDIT_WATCH_MODEL_EVENTS = True
DJANGO_EASY_AUDIT_WATCH_AUTH_EVENTS = True
DJANGO_EASY_AUDIT_WATCH_REQUEST_EVENTS = False
DJANGO_EASY_AUDIT_UNREGISTERED_URLS_DEFAULT = [r'^/static/',
                                               r'^/favicon.ico$',
                                               r'^/media/',
                                               r'^/__debug__/',
                                               r'^/ckeditor5/',
                                               ]

TIME_INPUT_FORMATS = "%H:%M"

SHOP_DISPLAY_ORDER = [
    "買取商店",
    "海峡通信",  # shop2　　　      ２
    "買取一丁目",  # shop3         ３
    "モバイルミックス",  # shop4    4
    "森森買取",  # shop5           ５
    "買取ルデヤ",  # shop6         ６
    "買取wiki",  # shop8          ７
    "買取ホムラ",  # shop7         ８
    "ドラゴンモバイル",  # shop10　　９
    "モバステ",  # shop11　         10
    "アキモバ",  # shop9           11
    "トゥインクル",  # shop12        12
    "家電市場",  # shop13           13
    "買取楽園",  # shop14           14
    "買取当番",  # shop15           15
    "携帯空間",  # shop16           16
    "ゲストモバイル",  # shop17      17
    "買取オク",  # shop18            18
    "毎日買取",  # shop20           20
]

FX_API_KEYS = {
    "alphavantage": "AlphaVantageKey",
    "finnhub": "FinnhubKey",
    "twelvedata": "603d21df9b194d9daeaccd898cee72a3",
}

TREND_MAX_LOOKBACK_DAYS = 90
TREND_DB_MAX_WORKERS = 6
TREND_CPU_MAX_WORKERS = 0  # 0/None=自动核数
TREND_DOWNSAMPLE_TARGET = 0  # 每条曲线最多点数（0=关闭）

LIST_ORDER = [
    "iphone-17-pro-max-256",
    "iphone-17-pro-max-512",
    "iphone-17-pro-max-1024",
    "iphone-17-pro-max-2048",
    "iphone-17-pro-256",
    "iphone-17-pro-512",
    "iphone-17-pro-1024",
    "iphone-Air-256",
    "iphone-Air-512",
    "iphone-Air-1024",
    "iphone-17-256",
    "iphone-17-512"
]

LOGIN_EXEMPT_URLS = [
    r'^AppleStockChecker/purchasing-price-records/ingest-json/?$',  # ← 新接口
    # 如还有 path-token 版/webhook 版，也一并加上
    r'^AppleStockChecker/purchasing-price-records/ingest-webscraper/?$',
    r'^AppleStockChecker/purchasing-price-records/ingest-webscraper/[-A-Za-z0-9_]+/?$',
]

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [("127.0.0.1", 6379)]},
    }
}

ASGI_APPLICATION = "config.asgi.application"
DATA_UPLOAD_MAX_MEMORY_SIZE=10 * 1024 * 1024

# ============================================================
# 买方库存风控决策配置 (BuyRisk)
# ============================================================

# === 适配现有"价格序列/库存"表的映射 ===
# 价格 15m 表（必须）：如 AppleStockChecker.PurchasingShopTimeAnalysis
BUY_RISK_PRICE_MODEL = "AppleStockChecker.PurchasingShopTimeAnalysis"
BUY_RISK_PRICE_TIME_FIELD = "timestamp"           # DateTimeField/DateTimeTZ
BUY_RISK_PRICE_VALUE_FIELD = "price_resale"       # Decimal/Float：收购价
BUY_RISK_PRICE_SKU_FIELD = "sku"                  # Char/ForeignKey
BUY_RISK_PRICE_WINDOW_DAYS = 7                    # 近 N 天用于 μ/σ 估计
BUY_RISK_PRICE_STEP_MINUTES = 15                  # 采样步长（用于 τ→步数）

# 库存（可选）：若你的项目已有库存表就填它；不填则用 buyrisk.InventoryLot
BUY_RISK_INVENTORY_MODEL = None
BUY_RISK_INVENTORY_SKU_FIELD = "sku"
BUY_RISK_INVENTORY_COST_FIELD = "cost"
BUY_RISK_INVENTORY_STATUS_FIELD = "status"
BUY_RISK_INVENTORY_STATUS_VALUES = ["in_stock", "ready"]

# SKU 列表（可选）：留空则从价格表 distinct 取
BUY_RISK_SKUS = []

# === 默认参数（无训练数据时启用；训练后会被模型参数覆盖）===
BUY_RISK_DEFAULTS = {
    "tau_hours": 2.0,           # 清货时长 τ
    "q": 0.95,                  # 左尾分位
    "alpha": 120.0,             # 卖-买固定价差
    "beta": 1.0,                # 卖-买比例
    "d_liq": 30.0,              # 极速清货折价
    "cost_per_unit": 100.0,     # 单位成本
    "min_margin": 150.0,        # 最小利润
    "fx_buffer": 20.0,          # FX 缓冲
    "i_star": 150.0,            # 目标库存
    "lambda_I": 1.0,            # 库存惩罚（每超一件降价）
    "b_ref": 3000.0,            # 供给曲线参考价
    "lambda_ref": 6.0,          # 参考到货率（件/小时）
    "b_elastic": 0.30,          # 每 +¥100 的指数弹性
    "q_star": 12.0,             # 目标进货（件/小时）
    "fx_sigma_daily": 0.008     # FX 日波动（无 FX 数据时）
}

# === Celery Beat 定时任务（已有 CELERY_BEAT_SCHEDULE 可追加）===
# 注意：如果项目中已经定义了 CELERY_BEAT_SCHEDULE，需要合并而不是覆盖
if 'CELERY_BEAT_SCHEDULE' not in locals():
    CELERY_BEAT_SCHEDULE = {}

CELERY_BEAT_SCHEDULE.update({
    # 每 15 分钟跑一次全量 SKU 决策
    "buyrisk_compute_all_skus_15m": {
        "task": "buyrisk.tasks.compute_all_skus",
        "schedule": 60 * 15,  # 15分钟
    },
    # 每日 03:30 训练
    "buyrisk_train_daily": {
        "task": "buyrisk.tasks.train_models_all_skus",
        "schedule": 60 * 60 * 24,  # 每天一次，可配合 crontab
    },
    # 每日 04:10 覆盖率回测
    "buyrisk_backtest_daily": {
        "task": "buyrisk.tasks.backtest_coverage_all_skus",
        "schedule": 60 * 60 * 24,  # 每天一次
    },
})

