"""
Django settings for YamagotiProjects project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3(&zari4^u-6iv$+z_2r2(oviwyj5g#cy*3c$t#x_=-w7cijv1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".ngrok-free.app", ]

# Application definition

INSTALLED_APPS = [
    'simplepro',
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'AppleStockChecker.apps.ApplestockcheckerConfig',
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
'easyaudit',

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    "YamagotiProjects.middleware.login_required.LoginRequiredMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
'easyaudit.middleware.easyaudit.EasyAuditMiddleware',
    'simplepro.middlewares.SimpleMiddleware'
]

ROOT_URLCONF = 'YamagotiProjects.urls'

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

try:
    if DEBUG:  # noqa: F821
        REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append(
            "rest_framework.renderers.BrowsableAPIRenderer"
        )
except NameError:
    pass

# ---- SimpleJWT ----
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # 如需与环境变量 SECRET_KEY 分离，可自定义 SIGNING_KEY
    # "SIGNING_KEY": os.getenv("JWT_SECRET", SECRET_KEY),
}

# ---- OpenAPI 文档 ----
SPECTACULAR_SETTINGS = {
    "TITLE": "Project API",
    "DESCRIPTION": "Django REST Framework + JWT",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [{"BearerAuth": []}],  # 文档右上角 Authorize 会显示 BearerAuth
    "COMPONENT_SPLIT_REQUEST": True,
}

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    # 部署后把前端域名加进来
]
# 若你在本地调试 CSRF：
CSRF_TRUSTED_ORIGINS = ["http://localhost:3000", "http://127.0.0.1:3000",
                        "http://127.0.0.1:8000/AppleStockChecker/dashboard/"]

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

WSGI_APPLICATION = 'YamagotiProjects.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
#
# USE_SQLITE = os.getenv("USE_SQLITE", "0").lower() in {"1", "true", "t", "yes", "y"}
# SQLITE_PATH = os.getenv("SQLITE_PATH", str(BASE_DIR / "db.sqlite3"))
#
# if USE_SQLITE:
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.sqlite3",
#             "NAME": SQLITE_PATH,   # 例如 /app/data/db.sqlite3
#         }
#     }
# else:
#     DATABASES = {
#         "default": {
#             "ENGINE": "django.db.backends.postgresql",
#             "NAME": os.getenv("POSTGRES_DB"),
#             "USER": os.getenv("POSTGRES_USER"),
#             "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
#             "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
#             "PORT": int(os.getenv("POSTGRES_PORT", "5432")),
#         }
#     }
#
# # 小建议：开启原子请求（SQLite 写入更稳）
# DATABASES["default"]["ATOMIC_REQUESTS"] = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EXTERNAL_TRADEIN_SOURCES = [
    # {"name": "shop10", "url": "https://api.webscraper.io/api/v1/scraping-job/34172531/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    {"name": "shop9",
     "url": "https://api.webscraper.io/api/v1/scraping-job/34172581/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop8", "url": "https://api.webscraper.io/api/v1/scraping-job/34171950/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop7", "url": "https://api.webscraper.io/api/v1/scraping-job/34172579/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop6-1", "url": "https://api.webscraper.io/api/v1/scraping-job/34172574/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop6-2", "url": "https://api.webscraper.io/api/v1/scraping-job/34172575/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop6-3", "url": "https://api.webscraper.io/api/v1/scraping-job/34172576/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop6-4", "url": "https://api.webscraper.io/api/v1/scraping-job/34172578/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop5-1",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172561/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop5-2",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172563/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop5-3",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172572/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop5-4",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172573/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop4",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/	34172559/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    {"name": "shop3",
     "url": "https://api.webscraper.io/api/v1/scraping-job/34172550/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    {"name": "shop2",
     "url": "https://api.webscraper.io/api/v1/scraping-job/34478442/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},

    # # 样例：B 平台
    # {"name": "shop10", "url": "https://api.webscraper.io/api/v1/scraping-job/34172531/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
]

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# 优先级：settings > 环境变量 > 项目内默认文件
EXTERNAL_IPHONE17_INFO_PATH = BASE_DIR / "AppleStockChecker" / "data" / "iphone17_info.csv"

# WebScraper Cloud API 访问令牌（在 Web Scraper Cloud 的 API 页面可见）
WEB_SCRAPER_API_TOKEN = "vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"

# 导出地址模板（如官方变更，可在这里改）
# WEB_SCRAPER_EXPORT_URL_TEMPLATE = "https://api.webscraper.io/api/v1/scraping-job/{job_id}/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"
WEB_SCRAPER_EXPORT_URL_TEMPLATE = "https://api.webscraper.io/api/v1/scraping-job/{job_id}/csv"

# Webhook 共享密钥：在 WebScraper Cloud 的 webhook URL 上带 ?token=XXXX，或在 Header 里带 X-Webhook-Token
WEB_SCRAPER_WEBHOOK_TOKEN = "0BkhVQJQPDe4IPfxfnw9bX8hYzxY29D48uGi8zq8TcjbsMIvXShEzaEJFFAj"

# 可选：把 WebScraper 的 sitemap 名 或 job 上的 custom_id 映射为清洗器名（shop3/shop4…）
WEB_SCRAPER_SOURCE_MAP = {
    "shop2": "shop2",
    "shop10": "shop10",
    "shop3": "shop3",
    "shop4": "shop4",
    "shop5-1": "shop5-1",
    "shop5-2": "shop5-2",
    "shop5-3": "shop5-3",
    "shop5-4": "shop5-4",
    "shop6-1": "shop6-1",
    "shop6-2": "shop6-2",
    "shop6-3": "shop6-3",
    "shop6-4": "shop6-4",
    "shop7": "shop7",
    "shop8": "shop8",
    "shop9": "shop9",
}

# 部属用
# WEB_SCRAPER_WEBHOOK_TOKEN = os.getenv("WEB_SCRAPER_WEBHOOK_TOKEN", "")

# 开发用
WEB_SCRAPER_WEBHOOK_TOKEN = "XNgCZCQN7dvkSP7K17xmK8aq-6_bjvI_"

# Celery/Redis
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", "redis://127.0.0.1:6379/0")
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TASK_TIME_LIMIT = 600
CELERY_TASK_SOFT_TIME_LIMIT = 540
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Tokyo"
CELERY_ENABLE_UTC = False

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
                    'code', 'subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|', 'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable', ],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side', '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells',
                               'tableProperties', 'tableCellProperties'],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h3', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h5', 'title': 'Heading 3', 'class': 'ck-heading_heading3'},

            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}
SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_ACTION = True
SIMPLEUI_ANALYSIS = False

SIMPLEPRO_SECRET_KEY = '2c4411a795534e0fbc28720051161434'
SIMPLEPRO_MONIT_DISPLAY = True
SIMPLEPRO_INFO = True
SIMPLEPRO_FK_ASYNC_DATA = True

# SIMPLEUI_HOME_PAGE = "/admin-home"
# SIMPLEUI_HOME_ICON = 'fa fa-user'

SIMPLEUI_CONFIG = {
    'system_keep': True,
    'dynamic': False,
    'menu_display': ['iPhone関連データ', ],
    'menus':
        [
            {
                'name': 'iPhone関連データ',
                'icon': 'fa-solid fa-mobile-screen-button',
                'models': [{'name': '中古店価格推移(PN別)',
                            'icon': 'fa-solid fa-chart-line',
                            'url': '/AppleStockChecker/resale-trend-pn-merged/',
                            },
                           {'name': '中古店価格推移(Model別)',
                            'icon': 'fa-solid fa-chart-line',
                            'url': '/AppleStockChecker/resale-trend-colors-merged/',
                            },
                           {'name': '中古店価格ボード',
                            'icon': 'fa-solid fa-table-columns',
                            'url': '/AppleStockChecker/price-matrix/',
                            },
                           {'name': 'iPhone公式在庫表',
                            'icon': 'fa-solid fa-warehouse',
                            'url': '/AppleStockChecker/price-matrix/',
                            },

                           {'name': '中古店価格メタデータ',
                            'icon': 'fa-solid fa-database',
                            'models': [{'name': 'iPhoneモデル',
                                        'icon': 'fa-solid fa-mobile-button',
                                        'url': '/admin/AppleStockChecker/iphone/',
                                        },
                                       {'name': '中古店',
                                        'icon': 'fa-solid fa-shop',
                                        'url': '/admin/AppleStockChecker/secondhandshop/'
                                        },
                                       {'name': '中古店価格記録',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/purchasingshoppricerecord/'
                                        },
                                       ]
                            },
                           {'name': 'iPhone公式在庫メタデータ',
                            'icon': 'fa-solid fa-file-contract',
                            'models': [{'name': 'Apple公式ストア',
                                        'icon': 'fa-solid fa-store',
                                        'url': '/admin/AppleStockChecker/officialstore/',
                                        },
                                       {'name': 'iphone官方在库記録',
                                        'icon': 'fa-solid fa-truck-ramp-box',
                                        'url': '/admin/AppleStockChecker/inventoryrecord/'
                                        },
                                       ]
                            },
                           # {'name': 'TryForSomething',
                           #  'icon': 'fa-solid fa-file-contract',
                           #  'models': [{'name': 'chatjs',
                           #              'icon': 'fa-solid fa-store',
                           #              'url': '/AppleStockChecker/template-chartjs/',
                           #              },
                           #             {'name': 'iphone官方在库記録',
                           #              'icon': 'fa-solid fa-truck-ramp-box',
                           #              'url': '/admin/AppleStockChecker/inventoryrecord/'
                           #              },
                           #             ]
                           #  },
                           ]
            },

        ]}

# --- 本地开发：允许 Session 认证 + JWT；生产保持只有 JWT ---
if os.getenv("DJANGO_ENV", "dev") == "dev":
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework.authentication.SessionAuthentication",  # 浏览器登录态
            "rest_framework_simplejwt.authentication.JWTAuthentication",  # 保留 JWT
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticated",
        ],
    }
else:
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework_simplejwt.authentication.JWTAuthentication",
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticated",
        ],
    }


DJANGO_EASY_AUDIT_WATCH_MODEL_EVENTS = True
DJANGO_EASY_AUDIT_WATCH_AUTH_EVENTS = True
DJANGO_EASY_AUDIT_WATCH_REQUEST_EVENTS = False
DJANGO_EASY_AUDIT_UNREGISTERED_URLS_DEFAULT = [r'^/static/',
                                               r'^/favicon.ico$',
                                               r'^/media/',
                                               r'^/__debug__/',
                                               r'^/ckeditor5/',
                                               ]


TIME_INPUT_FORMATS = "%H:%M"


SHOP_DISPLAY_ORDER = [

    "海峡通信",  # shop2　　　      ２
    "買取一丁目",  # shop3         ３

    "森森買取",  # shop5           ５
    "買取ルデヤ",  # shop6         ６
    "買取wiki",  # shop8          ７
    "買取ホムラ",  # shop7         ８
    "ドラゴンモバイル",  # shop10　　９
    "モバステ",  # shop11　         10
    "アキモバ",  # shop9           11
    "トゥインクル", # shop12        12
    "家電市場", # shop13           13
    "買取楽園", # shop14           14
    "買取当番", # shop15           15
    "携帯空間", # shop16           16
    # "",  # shop17               17
    # "",  # shop18               18
    # "",  # shop19               19
    "毎日買取", # shop20           20
    # "",  # shop21
    # "",  # shop22
    # "",  # shop23
    # "",  # shop24
    # "",  # shop25
]


FX_API_KEYS = {
    "alphavantage": "AlphaVantageKey",
    "finnhub": "FinnhubKey",
    "twelvedata": "603d21df9b194d9daeaccd898cee72a3",
}


TREND_MAX_LOOKBACK_DAYS = 90
TREND_DB_MAX_WORKERS    = 6
TREND_CPU_MAX_WORKERS   = 0    # 0/None=自动核数
TREND_DOWNSAMPLE_TARGET = 1500 # 每条曲线最多点数（0=关闭）



LIST_ORDER = [
    "iphone-17-pro-max-256",
    "iphone-17-pro-max-512",
    "iphone-17-pro-max-1024",
    "iphone-17-pro-max-2048",
    "iphone-17-pro-256",
    "iphone-17-pro-512",
    "iphone-17-pro-1024",
    "iphone-Air-256",
    "iphone-Air-512",
    "iphone-Air-1024",
    "iphone-17-256",
    "iphone-17-512"
]