"""
Django settings for YamagotiProjects project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "dev")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() in {"1", "true", "t", "yes", "y"}

ALLOWED_HOSTS = [h for h in os.getenv("DJANGO_ALLOWED_HOSTS", "").split(",") if h]

# Application definition

INSTALLED_APPS = [
    "channels",
    'simplepro',
    'simpleui',
    'import_export',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'AppleStockChecker.apps.ApplestockcheckerConfig',
    "corsheaders",
    "rest_framework",
    "drf_spectacular",
    "django_celery_beat",     # 定时任务(可在Admin里改间隔/暂停)
    "django_celery_results",  # 可选：任务结果持久化到DB
    "django_filters",

]

MIDDLEWARE = [
    'django.middleware.locale.LocaleMiddleware',  
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # "YamagotiProjects.middleware.login_required.LoginRequiredMiddleware",
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'simplepro.middlewares.SimpleMiddleware'
]

ROOT_URLCONF = 'YamagotiProjects.urls'

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
    ],
}

try:
    if DEBUG:  # noqa: F821
        REST_FRAMEWORK["DEFAULT_RENDERER_CLASSES"].append(
            "rest_framework.renderers.BrowsableAPIRenderer"
        )
except NameError:
    pass

# ---- SimpleJWT ----
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    # 如需与环境变量 SECRET_KEY 分离，可自定义 SIGNING_KEY
    "SIGNING_KEY": os.getenv("JWT_SECRET", SECRET_KEY),
}

# ---- OpenAPI 文档 ----
SPECTACULAR_SETTINGS = {
    "TITLE": "Project API",
    "DESCRIPTION": "Django REST Framework + JWT",
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    "SECURITY": [{"BearerAuth": []}],  # 文档右上角 Authorize 会显示 BearerAuth
    "COMPONENT_SPLIT_REQUEST": True,
}

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "https://yamaguti.ngrok.io",
    "https://*.ngrok.io",
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    # 部署后把前端域名加进来
]
# 若你在本地调试 CSRF：
CSRF_TRUSTED_ORIGINS = [os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "")]

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = "Lax"
CSRF_COOKIE_SAMESITE = "Lax"


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'YamagotiProjects.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


USE_SQLITE = os.getenv("USE_SQLITE", "0").lower() in {"1", "true", "t", "yes", "y"}
SQLITE_PATH = os.getenv("SQLITE_PATH", str(BASE_DIR / "db.sqlite3"))

if USE_SQLITE:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": SQLITE_PATH,  # 例如 /app/data/db.sqlite3
        }
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
            "PORT": int(os.getenv("POSTGRES_PORT", "5432")),
            "CONN_MAX_AGE": 400, 
            "OPTIONS": {
            "connect_timeout": 5,
            # 开 TCP keepalive，防中间网络设备闲置断链
            "options": "-c tcp_keepalives_idle=60 -c tcp_keepalives_interval=30 -c tcp_keepalives_count=5",
            # 长任务时别让 PG 端主动断你的语句/事务（按需调整）
            "options": "-c statement_timeout=0 -c idle_in_transaction_session_timeout=0 "
                       "-c tcp_keepalives_idle=60 -c tcp_keepalives_interval=30 -c tcp_keepalives_count=5",
        },
            
        }
    }

## 小建议：开启原子请求（SQLite 写入更稳）
#DATABASES["default"]["ATOMIC_REQUESTS"] = True

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja-jp'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = f"{os.getenv('URL_PREFIX', '')}/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
MEDIA_URL = f"{os.getenv('URL_PREFIX', '')}/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EXTERNAL_TRADEIN_SOURCES = [
    # {"name": "shop10", "url": "https://api.webscraper.io/api/v1/scraping-job/34172531/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    {"name": "shop9",
     "url": "https://api.webscraper.io/api/v1/scraping-job/34172581/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop8", "url": "https://api.webscraper.io/api/v1/scraping-job/34171950/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop7", "url": "https://api.webscraper.io/api/v1/scraping-job/34172579/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop6-1", "url": "https://api.webscraper.io/api/v1/scraping-job/34172574/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop6-2", "url": "https://api.webscraper.io/api/v1/scraping-job/34172575/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop6-3", "url": "https://api.webscraper.io/api/v1/scraping-job/34172576/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop6-4", "url": "https://api.webscraper.io/api/v1/scraping-job/34172578/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop5-1",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172561/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop5-2",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172563/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop5-3",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172572/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop5-4",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172573/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop4",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/	34172559/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    {"name": "shop3",
     "url": "https://api.webscraper.io/api/v1/scraping-job/34172550/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
    # {"name": "shop2",
    #  "url": "https://api.webscraper.io/api/v1/scraping-job/34172531/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},

    # # 样例：B 平台
    # {"name": "shop10", "url": "https://api.webscraper.io/api/v1/scraping-job/34172531/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"},
]

from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

# 优先级：settings > 环境变量 > 项目内默认文件
EXTERNAL_IPHONE17_INFO_PATH = BASE_DIR / "AppleStockChecker" / "data" / "iphone17_info.csv"

# WebScraper Cloud API 访问令牌（在 Web Scraper Cloud 的 API 页面可见）
WEB_SCRAPER_API_TOKEN = "YNndD5WeM3UFO32RKdrogf2p4hNVPlZE3r3rLCoHD3B4idpJcjyqRJbNndXM"

# 导出地址模板（如官方变更，可在这里改）
# WEB_SCRAPER_EXPORT_URL_TEMPLATE = "https://api.webscraper.io/api/v1/scraping-job/{job_id}/csv?api_token=vrbBYdfX805GgpQoDfgyPcm45QMoEx6ygvkfHohjo3CJBky7qO0oiFbXUjAp"
WEB_SCRAPER_EXPORT_URL_TEMPLATE = "https://api.webscraper.io/api/v1/scraping-job/{job_id}/csv"

# Webhook 共享密钥：在 WebScraper Cloud 的 webhook URL 上带 ?token=XXXX，或在 Header 里带 X-Webhook-Token
WEB_SCRAPER_WEBHOOK_TOKEN = "x2fcby15Mdai5xJqFm5A67Xyu9z14YQGnyGNWt4omOVm7DQBoPgHbWzap7VF"

# 可选：把 WebScraper 的 sitemap 名 或 job 上的 custom_id 映射为清洗器名（shop3/shop4…）
WEB_SCRAPER_SOURCE_MAP = {
    "shop1": "shop1",
    "shop2": "shop2",
    "shop3": "shop3",
    "shop4": "shop4",
    "shop5-1": "shop5-1",
    "shop5-2": "shop5-2",
    "shop5-3": "shop5-3",
    "shop5-4": "shop5-4",
    "shop6-1": "shop6-1",
    "shop6-2": "shop6-2",
    "shop6-3": "shop6-3",
    "shop6-4": "shop6-4",
    "shop7": "shop7",
    "shop8": "shop8",
    "shop9": "shop9",
    "shop10": "shop10",
    "shop11": "shop11",
    "shop12": "shop12",
    "shop13": "shop13",
    "shop14": "shop14",
    "shop15": "shop15",
    "shop16": "shop16",
    "shop17": "shop17",
    "shop18": "shop18",
    "shop19": "shop19",
    "shop20": "shop20",
}

# 部属用
# WEB_SCRAPER_WEBHOOK_TOKEN = os.getenv("WEB_SCRAPER_WEBHOOK_TOKEN", "")

# 开发用
WEB_SCRAPER_WEBHOOK_TOKEN = "XNgCZCQN7dvkSP7K17xmK8aq-6_bjvI_"

REDIS_URL = os.getenv("REDIS_URL", "redis://redis::6379/0")
REDIS_URL_RESULT = os.getenv("REDIS_URL_RESULT", "redis://redis::6379/1")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": ["redis://redis:6379/1"],  },
    }
}



# Celery/Redis
CELERY_BROKER_URL = os.getenv("CELERY_BROKER_URL", REDIS_URL)
CELERY_RESULT_BACKEND = os.getenv("CELERY_RESULT_BACKEND", CELERY_BROKER_URL)
CELERY_TASK_TIME_LIMIT = 600
CELERY_TASK_SOFT_TIME_LIMIT = 540
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = "Asia/Tokyo"
CELERY_ENABLE_UTC = False

USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

customColorPalette = [
    {
        'color': 'hsl(4, 90%, 58%)',
        'label': 'Red'
    },
    {
        'color': 'hsl(340, 82%, 52%)',
        'label': 'Pink'
    },
    {
        'color': 'hsl(291, 64%, 42%)',
        'label': 'Purple'
    },
    {
        'color': 'hsl(262, 52%, 47%)',
        'label': 'Deep Purple'
    },
    {
        'color': 'hsl(231, 48%, 48%)',
        'label': 'Indigo'
    },
    {
        'color': 'hsl(207, 90%, 54%)',
        'label': 'Blue'
    },
]

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': ['heading', '|', 'bold', 'italic', 'link',
                    'bulletedList', 'numberedList', 'blockQuote', 'imageUpload', ],

    },
    'extends': {
        'blockToolbar': [
            'paragraph', 'heading1', 'heading2', 'heading3',
            '|',
            'bulletedList', 'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': ['heading', '|', 'outdent', 'indent', '|', 'bold', 'italic', 'link', 'underline', 'strikethrough',
        'code','subscript', 'superscript', 'highlight', '|', 'codeBlock', 'sourceEditing', 'insertImage',
                    'bulletedList', 'numberedList', 'todoList', '|',  'blockQuote', 'imageUpload', '|',
                    'fontSize', 'fontFamily', 'fontColor', 'fontBackgroundColor', 'mediaEmbed', 'removeFormat',
                    'insertTable',],
        'image': {
            'toolbar': ['imageTextAlternative', '|', 'imageStyle:alignLeft',
                        'imageStyle:alignRight', 'imageStyle:alignCenter', 'imageStyle:side',  '|'],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]

        },
        'table': {
            'contentToolbar': [ 'tableColumn', 'tableRow', 'mergeTableCells',
            'tableProperties', 'tableCellProperties' ],
            'tableProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            },
            'tableCellProperties': {
                'borderColors': customColorPalette,
                'backgroundColors': customColorPalette
            }
        },
        'heading' : {
            'options': [
                { 'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph' },
                { 'model': 'heading1', 'view': 'h1', 'title': 'Heading 1', 'class': 'ck-heading_heading1' },
                { 'model': 'heading2', 'view': 'h3', 'title': 'Heading 2', 'class': 'ck-heading_heading2' },
                { 'model': 'heading3', 'view': 'h5', 'title': 'Heading 3', 'class': 'ck-heading_heading3' }
            ]
        }
    },
    'list': {
        'properties': {
            'styles': 'true',
            'startIndex': 'true',
            'reversed': 'true',
        }
    }
}



# AUTH_USER_MODEL = "dashboards.ApplicationUser"
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/AppleStockChecker/"          # 登录后跳这里（按需改）
LOGOUT_REDIRECT_URL = "/accounts/login/"

SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"




SIMPLEUI_HOME_INFO = False
SIMPLEUI_HOME_ACTION = True
SIMPLEUI_ANALYSIS = False

SIMPLEPRO_SECRET_KEY = '2c4411a795534e0fbc28720051161434'
SIMPLEPRO_MONIT_DISPLAY = True
SIMPLEPRO_INFO = True
SIMPLEPRO_FK_ASYNC_DATA = True



SIMPLEUI_CONFIG = {
    'system_keep': True,
    'dynamic': False,
    'menu_display': ['iPhone関連データ', ],
    'menus':
        [
            {
                'name': 'iPhone関連データ',
                'icon': 'fa-solid fa-mobile-screen-button',
                'models': [
                           {'name': '価格推移实时图表',
                            'icon': 'fa-solid fa-store',
                            'url': '/AppleStockChecker/statistical-data-summary/',
                            },
                           {'name': '価格ボード(展示)',
                            'icon': 'fa-solid fa-table-columns',
                            'url': '/AppleStockChecker/price-matrix/',
                            },
                            
                           {'name': 'iPhone公式在庫表',
                            'icon': 'fa-solid fa-warehouse',
                            'url': '/AppleStockChecker/price-matrix/',
                            },

                           {'name': '中古店価格メタデータ',
                            'icon': 'fa-solid fa-database',
                            'models': [{'name': 'iPhoneモデル',
                                        'icon': 'fa-solid fa-mobile-button',
                                        'url': '/admin/AppleStockChecker/iphone/',
                                        },
                                       {'name': '中古店',
                                        'icon': 'fa-solid fa-shop',
                                        'url': '/admin/AppleStockChecker/secondhandshop/'
                                        },
                                       {'name': '中古店価格記録',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/purchasingshoppricerecord/'
                                        },
                                        {'name': '价格整形记录',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/purchasingshoptimeanalysis/'
                                        },

                                       {'name': '基础统计featuresnapshot-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/featuresnapshot/'
                                        },
                                       {'name': '参数空间featurespec-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/featurespec/'
                                        },

                                       {'name': '统计模型modelartifact-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/modelartifact/'
                                        },
                                       {'name': '预测模型forecastsnapshot-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/forecastsnapshot/'
                                        },
                                       {'name': 'cohortbar-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/cohortbar/'
                                        },

                                       {'name': '商品组合成员cohortmember-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/cohortmember/'
                                        },
                                       {'name': '商品组合cohort-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/cohort/'
                                        },
                                       {'name': 'overallbar-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/overallbar/'
                                        },
                                       {'name': '店铺组合成员shopweightitem-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/shopweightitem/'
                                        },
                                       {'name': '店铺组合shopweightprofile-data',
                                        'icon': 'fa-solid fa-money-check-dollar',
                                        'url': '/admin/AppleStockChecker/shopweightprofile/'
                                        },





                                       ]
                            },

                           {'name': 'iPhone公式在庫メタデータ',
                            'icon': 'fa-solid fa-file-contract',
                            'models': [{'name': 'Apple公式ストア',
                                        'icon': 'fa-solid fa-store',
                                        'url': '/admin/AppleStockChecker/officialstore/',
                                        },
                                       {'name': 'iphone官方在库記録',
                                        'icon': 'fa-solid fa-truck-ramp-box',
                                        'url': '/admin/AppleStockChecker/inventoryrecord/'
                                        },
                                       ]
                            },
                            {'name': '临时页面',
                            'icon': 'fa-solid fa-file-contract',
                            'models': [                                
                                        {'name': '価格推移(Model別)',
                                         'icon': 'fa-solid fa-chart-line',
                                         'url': '/AppleStockChecker/resale-trend-colors-merged/',
                                         },
                                        {'name': '周期任务',
                                        'icon': 'fa-solid fa-store',
                                        'url': '/admin/django_celery_beat/periodictask/',
                                        },
                                        {'name': '中古店価格推移(PN別)',
                                        'icon': 'fa-solid fa-chart-line',
                                        'url': '/AppleStockChecker/resale-trend-pn-merged/',
                                        },
                                       {'name': '価格ボード(社内)',
                                        'icon': 'fa-solid fa-table-columns',
                                        'url': '/AppleStockChecker/price-matrix/',
                                        },
                                        {'name': '间隔',
                                         'icon': 'fa-solid fa-chart-line',
                                         'url': '/admin/django_celery_beat/intervalschedule/',
                                         },
                                        {'name': '计划任务',
                                         'icon': 'fa-solid fa-chart-line',
                                         'url': '/admin/django_celery_beat/crontabschedule/',
                                         },
                                        {'name': '日程时间',
                                         'icon': 'fa-solid fa-chart-line',
                                         'url': '/admin/django_celery_beat/solarschedule/',
                                         },
                                        {'name': '定时',
                                         'icon': 'fa-solid fa-chart-line',
                                         'url': '/admin/django_celery_beat/clockedschedule/',
                                         },

                                        {'name': '周期性任务',
                                         'icon': 'fa-solid fa-chart-line',
                                         'url': '/admin/django_celery_beat/periodictask/',
                                         },
                                        {'name': '用户',
                                         'icon': 'fa-solid fa-chart-line',
                                         'url': '/admin/auth/user/',
                                         },
                                        {'name': '组',
                                         'icon': 'fa-solid fa-chart-line',
                                         'url': '/admin/auth/group/',
                                         },
                                       ]
                            },

                           ]
            },

        ]}






SESSION_EXPIRE_AT_BROWSER_CLOSE = True

DJANGO_EASY_AUDIT_WATCH_MODEL_EVENTS = True
DJANGO_EASY_AUDIT_WATCH_AUTH_EVENTS = True
DJANGO_EASY_AUDIT_WATCH_REQUEST_EVENTS = True
DJANGO_EASY_AUDIT_UNREGISTERED_URLS_DEFAULT = [r'^/admin/',
                                               r'^/ajax/',
                                               r'^/dashboards/',
                                               r'^/static/',
                                               r'^/favicon.ico$',
                                               r'^/media/',
                                               r'^/sp/',
                                               r'^/__debug__/',
                                               r'^/ckeditor5/',
                                               r'^/api-auth/',
                                               ]



# --- 本地开发：允许 Session 认证 + JWT；生产保持只有 JWT ---
if os.getenv("DJANGO_ENV", "dev") == "dev":
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework.authentication.SessionAuthentication",        # 浏览器登录态
            "rest_framework_simplejwt.authentication.JWTAuthentication",  # 保留 JWT
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticated",
        ],
    }
else:
    REST_FRAMEWORK = {
        "DEFAULT_AUTHENTICATION_CLASSES": [
            "rest_framework_simplejwt.authentication.JWTAuthentication",
        ],
        "DEFAULT_PERMISSION_CLASSES": [
            "rest_framework.permissions.IsAuthenticated",
        ],
    }

SHOP_DISPLAY_ORDER = [
    "買取商店",
    "海峡通信",  # shop2　　　      ２
    "買取一丁目",  # shop3         ３
    "モバイルミックス",  # shop4     4
    "森森買取",  # shop5           ５
    "買取ルデヤ",  # shop6         ６
    "買取wiki",  # shop8          ７
    "買取ホムラ",  # shop7         ８
    "ドラゴンモバイル",  # shop10　　９
    "モバステ",  # shop11　         10
    "アキモバ",  # shop9           11
    "トゥインクル",  # shop12        12
    "家電市場",  # shop13           13
    "買取楽園",  # shop14           14
    "買取当番",  # shop15           15
    "携帯空間",  # shop16           16
    "ゲストモバイル",  # shop17               17
    "買取オク",  # shop18               18
    # "",  # shop19               19
    "毎日買取",  # shop20           20
    # "",  # shop21
    # "",  # shop22
    # "",  # shop23
    # "",  # shop24
    # "",  # shop25
]



FX_API_KEYS = {
    "alphavantage": "AlphaVantageKey",
    "finnhub": "FinnhubKey",
    "twelvedata": "603d21df9b194d9daeaccd898cee72a3",
}

TREND_MAX_LOOKBACK_DAYS = 90
TREND_DB_MAX_WORKERS    = 6
TREND_CPU_MAX_WORKERS   = 0    # 0/None=自动核数
TREND_DOWNSAMPLE_TARGET = 0 # 每条曲线最多点数（0=关闭）

LIST_ORDER = [
    "iphone-17-pro-max-256",
    "iphone-17-pro-max-512",
    "iphone-17-pro-max-1024",
    "iphone-17-pro-max-2048",
    "iphone-17-pro-256",
    "iphone-17-pro-512",
    "iphone-17-pro-1024",
    "iphone-Air-256",
    "iphone-Air-512",
    "iphone-Air-1024",
    "iphone-17-256",
    "iphone-17-512"
]


LOGIN_EXEMPT_URLS = [
    r'^AppleStockChecker/purchasing-price-records/ingest-json/?$',  # ← 新接口
    # 如还有 path-token 版/webhook 版，也一并加上
    r'^AppleStockChecker/purchasing-price-records/ingest-webscraper/?$',
    r'^AppleStockChecker/purchasing-price-records/ingest-webscraper/[-A-Za-z0-9_]+/?$',
]



ASGI_APPLICATION = "config.asgi.application"
